CREATE TABLE SongAppearances (
    Episode_Number INT PRIMARY KEY,
    BFF BOOLEAN,
    Party_Talking BOOLEAN,
    Reach_the_Stars BOOLEAN,
    Higher BOOLEAN,
    Lolistep BOOLEAN,
    Never_Give_Up BOOLEAN,
    New_Star_Generation BOOLEAN,
    Celebrate BOOLEAN,
    Revolution BOOLEAN,
    We_are_Magic BOOLEAN,
    Goodbye_Friends BOOLEAN
);

INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('1', '1', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('2', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('3', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('4', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('6', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('7', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('8', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('9', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('10', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('11', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('12', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('13', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('14', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('15', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('16', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('17', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('18', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('19', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('20', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('21', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('22', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('23', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('24', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('25', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('26', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('27', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('28', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('29', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('30', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('31', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('32', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('33', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('34', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('35', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('36', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('37', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('38', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('39', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('40', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('41', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('42', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('43', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('44', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('45', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('46', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('47', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('48', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('49', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('50', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('51', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1');
INSERT INTO SongAppearances (Episode_Number, BFF, Party_Talking, Reach_the_Stars, Higher, Lolistep, Never_Give_Up, New_Star_Generation, Celebrate, Revolution, We_are_Magic, Goodbye_Friends) VALUES ('52', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0');